name: Update submodules

# Controls when the action will run.
on:
  # Allows you to run this workflow manually from the Actions tab
  schedule:
    - cron: "0 4 7 * *"  # 每月7号12点更新
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  # This workflow contains a single job called "update"
  update:
    runs-on: ubuntu-latest

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@master

      - name: Pull & update submodules recursively
        run: |
          git submodule init
          git submodule update --remote --merge

      - name: Check if submodule has changes
        id: check_changes
        run: echo "::set-output name=changes::$(git status --porcelain)"
      
      - name: Stop if no submodule changes
        run: |
          if [ -z "${{ steps.check_changes.outputs.changes }}" ]; then
            echo "No submodule changes detected. Stopping the workflow."
            exit 1
          fi

      - name: Create branch
        run: git checkout -b submodule-update

      - name: Commit changes
        run: |
          git config --global user.name "fsyv"
          git config --global user.email "fsyv.me@gmail.com"
          git add .
          git commit -am "Update submodules"

      - name: Push branch
        uses: ad-m/github-push-action@master
        with:
          branch: submodule-update
          github_token: ${{ secrets.GITHUB_TOKEN }}

      - name: Create pull request
        uses: peter-evans/create-pull-request@v6
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: update submodule
          title: Update submodule
          body: This PR updates the submodule.
          bbranch: submodule-update
          base: main
